### ISSUE TITLE
ja_jp.csvで変数のパーセント記号が全角になっていて置換されないものがある

### ISSUE THREAD

**Issue by tomoPola** [magentoj/language-ja_JP#5]
ja_JP.csvに、変数のパーセント記号が全角になっていて置換されないものがあり、Pull requestを出させていただきました、ご対応よろしくお願いします
https://github.com/magentoj/language-ja_JP/pull/4

**Comment by nozokada** [comment]
Fixed in https://github.com/magentoj/language-ja_JP/pull/4
